name: Deploy

on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: Install Pip packages
              run: |
                    python3 -m pip install --upgrade pip
                    pip install -r requirements.txt

            - name: Environment variables
              run: |
                    echo "GOV_API_KEY=${{ secrets.GOV_API_KEY }}" >> .env
            
            - name: Run Python script
              run: |
                    ls
                    ls site/
                    touch site/_data/bus_objects.yaml
                    python3 gov.py

            - name: Move to site
              run: cd site

            - name: Setup Pages
              uses: actions/configure-pages@v3

            - name: Build
              uses: actions/jekyll-build-pages@v1

            - name: Upload artifact
              uses: actions/upload-pages-artifact@v4
    
    # Deploy job
    deploy:
        # Add a dependency to the build job
        needs: build
    
        # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
        permissions:
            pages: write      # to deploy to Pages
            id-token: write   # to verify the deployment originates from an appropriate source
    
        # Deploy to the github-pages environment
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
    
        # Specify runner + deployment step
        runs-on: ubuntu-latest
        steps:
            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v4 # or specific "vX.X.X" version tag for this action

