name: Deploy

on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]
    workflow_dispatch:
    
    # Schedule a workflow to run every 15 minutes from 5am to 11pm, and then every hour thereafter
    # schedule:
    #     - cron: '*/5 5-22 * * *'
    #     - cron: '5 23,0-4 * * *'

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: Deployment
              uses: appleboy/ssh-action@v0.1.10
              with:
                host: ${{ secrets.SSH_HOST }}
                username: ${{ secrets.SSH_USER }}
                key: ${{ secrets.SSH_KEY }}
                port: 22
                command_timeout: 30m
                script: | 
                    cd /etc/open_bus/ && git restore /etc/open_bus/site/_layouts/home.html && git pull origin main && echo `date` > last_deploy.txt
                    GIT_SHA=`git rev-parse HEAD` && sed -i "s/COMMIT_SHA/$GIT_SHA/" /etc/open_bus/site/_layouts/home.html